version: "3"
services:
  laravel:
    build: ./TourTravelStore_BE # Đường dẫn đến Dockerfile của Laravel
    container_name: laravel-app
    ports:
      - "8000:80" # Laravel sẽ chạy trên port 8000
    volumes:
      - ./TourTravelStore_BE:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tourtravelstore
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tourtravelstore
    volumes:
      - db_data:/var/lib/mysql

  angular:
    build: ./TourTravelStore_FE # Đường dẫn đến Dockerfile của Angular
    container_name: angular-app
    ports:
      - "4200:80" # Angular sẽ chạy trên port 4200
    depends_on:
      - laravel

volumes:
  db_data:
